/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vitrinidatasoft.view;

import br.com.vitrinidatasoft.Listeners.MainMenuListener;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author mrhell
 */
public class MainMenu extends javax.swing.JFrame {
    
    private final MainMenuListener listener;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        listener = new MainMenuListener(this);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        lblBtnCliente = new javax.swing.JLabel();
        btnProduto = new javax.swing.JButton();
        lblBtnProduto = new javax.swing.JLabel();
        btnPedido = new javax.swing.JButton();
        lblBtnPedido = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblBtnSair = new javax.swing.JLabel();
        btnUltimosPedidos = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemProduto = new javax.swing.JMenuItem();
        menuItemPedido = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Cadastro de Contratos");
        setPreferredSize(new java.awt.Dimension(1028, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 100));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        lblTitle.setText("Sistema Controle de Contratos");
        lblTitle.setIconTextGap(30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_client.png"))); // NOI18N
        btnCliente.setActionCommand("OPEN_FORM_CLIENTE");
        btnCliente.setMaximumSize(new java.awt.Dimension(153, 139));
        btnCliente.setName("btnCliente"); // NOI18N

        lblBtnCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBtnCliente.setForeground(new java.awt.Color(0, 51, 255));
        lblBtnCliente.setText("Cliente");

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_products.png"))); // NOI18N
        btnProduto.setActionCommand("OPEN_FORM_PRODUTO");
        btnProduto.setName("btnProduto"); // NOI18N

        lblBtnProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBtnProduto.setForeground(new java.awt.Color(0, 51, 255));
        lblBtnProduto.setText("Produto");

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_pedido83px.png"))); // NOI18N
        btnPedido.setActionCommand("OPEN_FORM_PEDIDO");
        btnPedido.setMaximumSize(new java.awt.Dimension(153, 129));
        btnPedido.setMinimumSize(new java.awt.Dimension(153, 129));
        btnPedido.setName("pedido"); // NOI18N
        btnPedido.setPreferredSize(new java.awt.Dimension(153, 129));

        lblBtnPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBtnPedido.setForeground(new java.awt.Color(0, 51, 255));
        lblBtnPedido.setText("Pedido");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_sair.png"))); // NOI18N
        btnSair.setActionCommand("EXIT_SYSTEM");
        btnSair.setName("btnSair"); // NOI18N

        lblBtnSair.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBtnSair.setForeground(new java.awt.Color(0, 51, 255));
        lblBtnSair.setText("Sair");

        btnUltimosPedidos.setText("Ultimos Pedidos");
        btnUltimosPedidos.setActionCommand("OPEN_FORM_ULTIMOS_PEDIDOS");

        menuArquivo.setText("Arquivo");

        menuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu_client.png"))); // NOI18N
        menuItemCliente.setText("Cliente");
        menuItemCliente.setActionCommand("OPEN_FORM_CLIENTE");
        menuItemCliente.setName("menuItemCliente"); // NOI18N
        menuArquivo.add(menuItemCliente);
        menuItemCliente.getAccessibleContext().setAccessibleName("menuItemCliente");

        menuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu_produtos.png"))); // NOI18N
        menuItemProduto.setActionCommand("OPEN_FORM_PRODUTO");
        menuItemProduto.setLabel("Produto");
        menuItemProduto.setName("menuItemProduto"); // NOI18N
        menuArquivo.add(menuItemProduto);
        menuItemProduto.getAccessibleContext().setAccessibleName("menuItemProduto");

        menuItemPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu_pedido.png"))); // NOI18N
        menuItemPedido.setText("Pedido");
        menuItemPedido.setActionCommand("OPEN_FORM_PEDIDO");
        menuItemPedido.setName("menuItemPedido"); // NOI18N
        menuArquivo.add(menuItemPedido);
        menuItemPedido.getAccessibleContext().setAccessibleName("menuItemPedido");

        menuBar.add(menuArquivo);

        jMenu1.setText("Pesquisar");
        menuBar.add(jMenu1);

        menuSair.setText("Sair");
        menuSair.setActionCommand("EXIT_SYSTEM");
        menuSair.setName("menuItemSair"); // NOI18N
        menuBar.add(menuSair);
        menuSair.getAccessibleContext().setAccessibleName("menuItemSair");

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblBtnCliente)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblBtnProduto)
                        .addGap(76, 76, 76)
                        .addComponent(lblBtnPedido)
                        .addGap(288, 288, 288)
                        .addComponent(lblBtnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUltimosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUltimosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBtnCliente)
                    .addComponent(lblBtnProduto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBtnPedido)
                        .addComponent(lblBtnSair)))
                .addGap(101, 101, 101))
        );

        btnCliente.getAccessibleContext().setAccessibleName("btnCliente");
        btnProduto.getAccessibleContext().setAccessibleName("btnProduto");
        btnSair.getAccessibleContext().setAccessibleName("btnSair");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public JButton getBtnCliente() {
        return btnCliente;
    }

    public JButton getBtnPedido() {
        return btnPedido;
    }

    public JButton getBtnProduto() {
        return btnProduto;
    }

    public JButton getBtnSair() {
        return btnSair;
    }

    public JMenuItem getMenuItemCliente() {
        return menuItemCliente;
    }

    public JMenuItem getMenuItemProduto() {
        return menuItemProduto;
    }

    public JMenu getMenuSair() {
        return menuSair;
    }

    public JMenuItem getMenuItemPedido() {
        return menuItemPedido;
    }

    public JButton getBtnUltimosPedidos() {
        return btnUltimosPedidos;
    }
        
    
    public void centerScreen(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
                
        if ( frameSize.width > screenSize.width )
            frameSize.width = screenSize.width;
        
        if ( frameSize.height > screenSize.height )
            frameSize.height = screenSize.height;
            
        this.setLocation ( (screenSize.width - frameSize.width) >> 1  , 
                (screenSize.height - frameSize.height) >>  1 );
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                MainMenu mainMenu = new MainMenu();
                mainMenu.setLocationRelativeTo(null);
                mainMenu.centerScreen();
                mainMenu.setVisible(true);
                //DataBaseFactory.getInstance().close();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUltimosPedidos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBtnCliente;
    private javax.swing.JLabel lblBtnPedido;
    private javax.swing.JLabel lblBtnProduto;
    private javax.swing.JLabel lblBtnSair;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemPedido;
    private javax.swing.JMenuItem menuItemProduto;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
